name: Build and push to dockerhub
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build-and-push:
    name: Build web
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: schizo99/dnschecker

    - name: Get Next Version
      id: semver
      uses: ietf-tools/semver-action@v1
      with:
        token: ${{ github.token }}
        branch: main

    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        makeLatest: legacy
        name: ${{ steps.semver.outputs.next }}
        token: ${{ github.token }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: schizo99/dnschecker:${{ steps.semver.outputs.nextStrict }},schizo99/dnschecker:latest
